### ISSUE TITLE
Frontend. Lista vacilor fermierului

### ISSUE THREAD

**Issue by comptech-soft** [comptech-soft/reproplant#29]
- [ ] #1. Structura listei

![fermier - lista vaci - structura](https://user-images.githubusercontent.com/18272816/42735003-ba722cac-8855-11e8-9461-642f0688fb98.png)

- [ ] #2. Cautare dupa crotalie, numar scurt, etc

- [ ] #3. Filtrare dupa: rasa, validitate, activ|inactiv

- [ ] #4. Sortare dupa: ce se poate

- [ ] #5. Adaugarea unei vaci

![fermier - adaugarea unei vaci](https://user-images.githubusercontent.com/18272816/42735035-5e03018e-8856-11e8-8b1d-4d3e398a208a.png)

- [ ] #6. Adaugarea rapida unui taur

![adaugarea rapida a unui taur](https://user-images.githubusercontent.com/18272816/42735043-83d9cd2a-8856-11e8-8187-4eb94fc47521.png)

- [ ] #7. Adaugarea rapida a unei vaci
